server:
  port: 0 # 0으로 설정 시 0 ~ 65535중의 중복되지 않은 임의의 수로 설정

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: member-service
  redis:
    host: localhost
    port: 6379
  # 아래는 jdbc의 기본 db 관련 설정인데, jdbc 뿐만 아니라 mybatis / jpa 등 spring의 대부분의 DB 기술에 동일하게 사용
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/ordermsa
    username: root
    password: 1234
  jpa:
    database: mysql
    # innoDB를 쓰겠다 라는 설정
    database-platform: org.hibernate.dialect.MariaDBDialect
    # ddl 문 자동생성 여부 true. 테이블은 자동생성(반영)해주나, 스키마는 반드시 사전에 생성 필요
    generate-ddl: true
    # jpa(인터페이스)의 실질적인 구현체는 hibernate 이다.
    hibernate:
      # create : 매번 table을 drop후 재 생성
      # update : entity 변경사항만 alter를 적용하고 기존 데이터 유지
      # validate : 실제 DB와의 차이점을 check만 하고 ddl 문 실행 x, 콘솔로만 변경사항 출력.
      ddl-auto: create
    # 콘솔창에 ddl, dml 등의 쿼리를 출력하여 보여주는 옵션
    show_sql: true

jwt:
  expirationAt: 1000 # 1000분
  # 인코딩된 문자 32자 이상 필요. (특수문자 X)
  # beyondaccesstokensecretkeybeyondaccesstokensecretkeybeyondaccesstokensecretkey
  secretKeyAt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5
  expirationRt: 10000 # 10000분
  # 원래 아래 시크릿키 달라야 됨
  secretKeyRt: YmV5b25kYWNjZXNzdG9rZW5zZWNyZXRrZXliZXlvbmRhY2Nlc3N0b2tlbnNlY3JldGtleWJleW9uZGFjY2Vzc3Rva2Vuc2VjcmV0a2V5