# docker-compose 스크립트 문법에 대한 버전
version: '3.8'
services:
  mydb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=1234
      - MARIADB_DATABASE=ordersystem
    # 도커 컴포즈 네트워크 내에서는 외부포트 제거 가능
    # ports:
    #   - "3309:3306"
  myredis:
    image: redis
    # ports:
    #   - "6388:6379"
  myordersystem:
    build:
      context: ./ordersystem
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mydb
    restart: on-failure:1
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://mydb:3306/ordersystem
      - SPRING_REDIS_HOST=myredis